version: 0.2

phases:
  install:
    commands:
      - service docker start
  build:
    commands:
      - make bundle
      - |
          aws cloudformation package \
           --template-file template.yml \
           --output-template output.yml \
           --s3-bucket sam-todo-python \
           --s3-prefix $CODEBUILD_SOURCE_VERSION

artifacts:
  type: zip
  files:
    - output.yml

